config:
  lr: 2.0e-05
  seed: 123
  gradient_accumulation_steps: 1
  weight_decay: 0.01
  validation_metrics:
  - MRR@10
  - recall@100
  - recall@200
  - recall@500
  pretrained_no_yamlconfig: false
  nb_iterations: 80000
  train_batch_size: 16
  eval_batch_size: 16
  index_retrieve_batch_size: 16
  record_frequency: 10000
  train_monitoring_freq: 500
  warmup_steps: 6000
  max_length: 256
  fp16: true
  matching_type: splade
  monitoring_ckpt: MRR@10
  overwrite_final: true
  tokenizer_type: models/mlm_flops/DistilBERT
  top_k: 1000
  eval_metric:
  - - mrr_10
    - recall
  - - ndcg_cut
  - - mrr_10
    - recall
  - - ndcg_cut
  - - mrr_10
    - recall
  threshold: 0
  loss: KlDiv
  regularizer:
    FLOPS:
      lambda_d: 0.05
      T: 50000
      targeted_rep: rep
      reg: FLOPS
    L1:
      lambda_q: 0.005
      T: 50000
      targeted_rep: rep
      reg: L1
  checkpoint_dir: models/efficient/V/small_Ld_5e2/checkpoint
  index_dir: models/efficient/V/small_Ld_5e2/index
  out_dir: models/efficient/V/small_Ld_5e2/out
data:
  type: hard_negatives
  TRAIN:
    DATASET_PATH: data/msmarco/hard_negatives_scores/cross-encoder-ms-marco-MiniLM-L-6-v2-scores.pkl.gz
    D_COLLECTION_PATH: data/msmarco/full_collection
    Q_COLLECTION_PATH: data/msmarco/train_queries/queries
    QREL_PATH: data/msmarco/train_queries/qrels.json
  VALIDATION_FULL_RANKING:
    D_COLLECTION_PATH: data/msmarco/val_retrieval/collection
    Q_COLLECTION_PATH: data/msmarco/val_retrieval/queries
    QREL_PATH: data/msmarco/val_retrieval/qrel.json
    TOP_K: 500
  COLLECTION_PATH: data/msmarco/full_collection
  Q_COLLECTION_PATH:
  - data/msmarco/dev_queries
  - data/msmarco/TREC_DL_2019/queries_2019
  - data/msmarco/TREC_DL_2020/queries_2020
  EVAL_QREL_PATH:
  - data/msmarco/dev_qrel.json
  - data/msmarco/TREC_DL_2019/qrel.json
  - data/msmarco/TREC_DL_2019/qrel_binary.json
  - data/msmarco/TREC_DL_2020/qrel.json
  - data/msmarco/TREC_DL_2020/qrel_binary.json
  flops_queries: data/msmarco/all_dev_queries/
init_dict:
  model_type_or_dir: models/mlm_flops/DistilBERT
  model_type_or_dir_q: models/mlm_flops/DistilBERT
  freeze_d_model: 0
  agg: max
  fp16: true
